@PlatformService_HostAddress = http://localhost:5028
@id = 1

### Get all platforms
GET {{PlatformService_HostAddress}}/api/platforms
Accept: application/json

### Get platform by ID
GET {{PlatformService_HostAddress}}/api/platforms/{{id}}
Accept: application/json

### Create a new platform
POST {{PlatformService_HostAddress}}/api/platforms
Content-Type: application/json

{
  "name": "CommandLine",
  "publisher": "CLI",
  "cost": "Free"
}

###
